name: Patch
on:
  push:
    branches: [dev]

jobs:
  patch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: git config --global user.name 'Jack Bass'
      - run: git config --global user.email 'jack@bassj.io'
      - run: npm version patch 
      - run: git push

